### ISSUE TITLE
Weird install issues

### ISSUE THREAD

**Issue by Motzumoto** [Iapetus-11/better-statcord.py#11]
When I install `betterstatcord.py` through PyPI and through GitHub, I still get this error: 
```py
Traceback (most recent call last):
  File "/home/lain/.local/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 935, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lain/AGB/Cogs/tasks.py", line 11, in <module>
    from statcord import Client as StatcordClient
ModuleNotFoundError: No module named 'statcord'
```

I'm not entirely sure what to do, I do have basic statcord.py removed, so I'm not sure what's conflicting

**Comment by Iapetus-11** [comment]
How are you installing BetterStatcord (like what command) and how are you running your bot?

**Comment by Motzumoto** [comment]
> How are you installing BetterStatcord (like what command) and how are you running your bot?

`pip3 install betterstatcord.py` 

And why does how I run my bot matter? It's on my server

**Comment by Iapetus-11** [comment]
> And why does how I run my bot matter? It's on my server

I don't believe this is an issue with the library, but a user error instead. You may be installing the library for a different version of Python or outside of your virtual environment, which may be why you can't import it despite the install seemingly going fine.

If I were running my bot like `python3 my_bot.py`, I would run `python3 -m pip install betterstatcord.py` to install the library. I hope that helps, if it doesn't I'm not sure what else I could do to resolve this issue.

**Comment by Motzumoto** [comment]
I am doing exactly that
I've had this issue on my local pc and my server, so I can replicate it 

What's even funnier about this is that my bot is completely dockerized. So every time I relaunch it to update something that can't be reloaded with cogs, it re-installs its server and requirements. 

Showing me installing and making sure everything should work: https://agb-dev.xyz/u/hlTTQ3.mp4

After completely reinstalling WSL (it says using cached requirements because I forgot to add my config files lul): https://agb-dev.xyz/u/ewY8iW.mp4

It's also not just a wsl issue, same shit happens on Windows: https://agb-dev.xyz/u/eC8Tma.mp4

**Comment by Iapetus-11** [comment]
Ahhh I figured out the issue, there is no `Client` class, it's `StatcordClient`. Sorry it took me so long to realize, I haven't worked on/looked at this project in ages.
<img width="717" alt="image" src="https://user-images.githubusercontent.com/38477514/205472003-b739b224-fe8d-4971-88c6-16075f2fa24f.png">

**Comment by Motzumoto** [comment]
Alright, can you update the examples before you forget

**Comment by Iapetus-11** [comment]
I believe the examples already all say StatcordClient

**Comment by Motzumoto** [comment]
> I believe the examples already all say StatcordClient

Huh, yeah they do, dang, guess I was using an old example. Thank you for your help.
