### ISSUE TITLE
Add an option to ignore certain users

### ISSUE THREAD

**Issue by TheMoksej** [Iapetus-11/better-statcord.py#2]
From looking at the code, I couldn't find a way to ignore specific user(s) commands. It'd be nice if there was a way to ignore specific user(s), so popular commands wouldn't get filled with owner-only or admin-only commands. I'm sure I'm not the only one who'd like to ignore specific user(s) :D

**Comment by Iapetus-11** [comment]
I might add this, for now you can subclass `StatcordClient` and override [`_command_ran`](https://github.com/Iapetus-11/betterstatcord.py/blob/main/statcord/client.py#L83-L96)

**Comment by Iapetus-11** [comment]
Seems to be a very niche problem, closing for now.
