### ISSUE TITLE
Unnecessary code duplication

### ISSUE THREAD

**Issue by circuitsacul** [Iapetus-11/better-statcord.py#3]
https://github.com/Iapetus-11/betterstatcord.py/blob/main/statcord/client.py#L129L143

This could be much simpler.
```py
       graphs = [self.custom_1, self.custom_2]
       values = {0: 0, 1: 0}
       for x, g in enumerate(graphs):
           if g is not None:
               value = g()
               if inspect.isawaitable(g):
                   value = await value
               if value:
                  values[x] = value
```

Then just access `values[0]` and `values[1]` instead of `custom_0_value` and `custom_1_value`

**Comment by Iapetus-11** [comment]
That's a bit messy but I get the point, I'll fix it.

**Comment by Iapetus-11** [comment]
Fixed in 1.3.0, now available on PYPI.

**Comment by circuitsacul** [comment]
Looks like your function called _call_custom_graph checks if `self.custom_1` is none/awaitable, instead of the callable passed. This means if I set `self.custom_1` to a non-awaitable and set `self.custom_2` to an awaitable, custom_1 will fail.

https://github.com/Iapetus-11/betterstatcord.py/blob/a4379ea8e7aaafa4cc6c2a9a72d4ed4f7fc8004a/statcord/client.py#L109

**Comment by Iapetus-11** [comment]
I can't believe I made that mistake damn I'm dumb, I'll fix it soon!
