### ISSUE TITLE
Support clustered endpoints

### ISSUE THREAD

**Issue by circuitsacul** [Iapetus-11/better-statcord.py#4]
Statcord supports clustered bots, where each cluster posts with its own unique id and then the stats are merged together. It would be nice if this lib supported that (the official lib doesn't).

Note that clustered endpoints are restricted, so you may have to get whitelisted first. API info here: <https://docs.statcord.com/#/api?id=post-clustered-stats>

**Comment by Iapetus-11** [comment]
This library is only for use with Discord.py. Unless you have a complex sharding solution there should be no need for this as Discord.py's AutoShardedBot basically runs all the shards in **one** big cluster anyways.

**Comment by circuitsacul** [comment]
discord.py allows for manual sharding, allowing me to launch multiple clusters. Like this:
```py
bot_instance_1 = commands.AutoShardedBot(shards=8, shard_ids=[0, 1, 2, 3])
bot_instance_2 = commands.AutoShardedBot(shards=8, shard_ids=[4, 5, 6, 7])
```
Then each instance can be launched in its own process.

**Comment by Iapetus-11** [comment]
I know you can do that. 
> Unless you have a complex sharding solution

I guess this is more common than I thought. It would be too complex to add this functionality into this library, so perhaps I'll make a seperate library specifically for bots which use clustering.

**Comment by circuitsacul** [comment]
All you would need is to use a different endpoint and then have the StatcordClient accept a cluster_id parameter, which you then post. Everything else would be the same, each StatcordClient with the stats for its cluster.

**Comment by Iapetus-11** [comment]
Oh, I didn't read the first comment in full. Yeah I can do that I'll do it Tuesday or Wednesday

**Comment by Iapetus-11** [comment]
Sorry this took so long, 2.0.3 is out which contains the `StatcordClusterClient` class which supports this feature.

**Comment by circuitsacul** [comment]
Thanks a lot
