### ISSUE TITLE
Support for discord.py2.0 developmental version

### ISSUE THREAD

**Issue by Dhruvacube** [Iapetus-11/better-statcord.py#8]

**Comment by Iapetus-11** [comment]
I'm not familiar with Discord.py 2.0, if you create a pull request with the necessary changes or tell me what needs to be done I can release a new version of BetterStatcord that supports 2.0.

**Comment by Dhruvacube** [comment]
sure @lapetus-11

**Comment by Dhruvacube** [comment]
I would actually close this issue since since betterstatcord.py 3.3.0 now supports discord.py2.0, thanks
